### ISSUE TITLE
x-www-form-urlencoded处理的问题

### ISSUE THREAD

**Issue by wjian2580** [HttpRunner/har2case#10]
`post_data = utils.x_www_form_urlencoded(post_data)`

拼接后生成的的用例:

`Code=18GYHC713&Id=102830&vpsToken=xV1phNlk9&Number=TJ280421&lId=5&content=asd`

测试发现对于`x-www-form-urlencoded`类型的数据不拼接也不影响请求，生成的yml用例反而更直观，方便维护

```
request:
    data:
        Code: 18GYHC713
        workId: '102829'
        Number: TJ233575
        vpsToken: xxx
    headers:
        Content-Type: application/x-www-form-urlencoded
```
